### ISSUE TITLE
Lack of licensing gives a default of "All rights reserved"

### ISSUE THREAD

**Issue by Benevolent27** [jochemstoel/nodejs-system-sleep#13]
Hi, I think this script is rather useful NPM module.  However the lack of a license means it has a default of being "all rights reserved".  This means nobody is legally permitted to utilize the code, copy it, or use it, with one exception that people can create a fork of your repository, as per the GitHub user agreement.  However, without the legal right given to actually utilize the code in any way, forking isn't really that useful.  If this is not intended, then it'd be really nice if there could be a license attached here. 

Here's an exerpt from git-hub's help documentation:
"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."
Source:  [https://help.github.com/articles/licensing-a-repository/](https://help.github.com/articles/licensing-a-repository/)

**Comment by jochemstoel** [comment]
Hi, @Benevolent27 

I added a _unlicense_ LICENSE.md file in this repository. This means you can use module system-sleep wherever you want without restrictions. I trust this answers your question.

**Comment by Benevolent27** [comment]
:D Sorry to be a bother!  I feel your intention with the "leave me out of it" was clear, but legal is as legal does. lol.  Thanks!

**Comment by sgustafsson** [comment]
could you also add the license information to the package.json file:

https://docs.npmjs.com/files/package.json#license
https://spdx.org/licenses/Unlicense.html

**Comment by jochemstoel** [comment]
When/if I feel like it.
