### ISSUE TITLE
error in webpack environment 

### ISSUE THREAD

**Issue by mostafa6765** [jochemstoel/nodejs-system-sleep#15]
`typeError: __webpack_require__(...).execSync is not a function`

Warning: Critical dependencies

* is this package useable with webpack?

**Comment by jochemstoel** [comment]
I'm sorry, @mostafa6765 but it is impossible to use system-sleep in any browser. Not with webpack, browserify or any other bundler.  _On a sidenote however, it does work in Electron/NW.js_

system-sleep works either by using [deasync ](https://github.com/abbr/deasync) (which is only for Node) and if that doesn't work falls back to executing a self closing child process synchronously which is also Node specific.  Browsers support neither of these methods.

If you are looking to delay script execution in a browser environment, I suggest you have a look at the new _async_ functions and see if awaiting a Promise does the trick for you.
Something along these lines:
```js
const sleep = milliseconds => new Promise(deliver => setTimeout(deliver, milliseconds))

async function test() {
    for(let i = 0; i < 10; i++) {
        await sleep(3000)
        console.log(i)
    }
}

test() // this will console log the value of i every 3 seconds
```
Asynchronous function do not require the _function_ keyword. You may also use async in arrow functions. So this works too:
```js
(async () => {
    await sleep(5000)
    console.log('done')
})()
```
Although _await_ waits for the value resolved by the Promise, you can not use them to return your async function. 
```js
// this will not work
async function loadFile(file) {
    var data = await loadFile(file) // suppose loadFile will ajax/fetch/xmlhttprequest or something
    return data
}
console.log(loadFile('myFile.xml'))   // undefined
```
