### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by guderkar** [jochemstoel/nodejs-system-sleep#2]
Hi, first of all I have to say I love the cunning way of doing sleep.
I think it's possible to make it working out of the box even for portable node.js binary. Here's the idea.
```javascript
function sleep (milliseconds)
{
        var exec = require('child_process').execSync;
	exec(process.execPath + " -e \"setTimeout(function () { return true; }, " + milliseconds + ");\"");
}
```

**Comment by jochemstoel** [comment]
Hello, guderkar. 

Thank you for your message. I was surprised to see that my package has so many downloads! It is very old. Your suggestion is correct and it works. However, I now have a better solution which is to use deasync.
I have updated the Github repository and NPM package on https://www.npmjs.com/package/system-sleep  and edited the readme. It now includes a test.js file too.

This will now work for everybody on every platform, portable Node or not.

Have a nice day and let me know if you need  help!
