### ISSUE TITLE
The first sleep time is affected by the setTime

### ISSUE THREAD

**Issue by Charder-uGym** [jochemstoel/nodejs-system-sleep#21]
A simple test.js, 
```
var sleep = require("system-sleep");

setTimeout(function() {
  console.log("Job done!");
}, 1000);

for (var i=0; i<5; i++){
  var now = Date.now();    
  sleep(200);
  console.log("sleep time(ms):", Date.now()-now);
}

console.log("Async job is done");
```
The output is interesting, 
```
>node test.js
Job done!
sleep time(ms): 1020
sleep time(ms): 204
sleep time(ms): 201
sleep time(ms): 201
sleep time(ms): 202
Async job is done
```
The first sleep time is 1020ms instead of 200ms specified. Change the timeout of setTime to 500ms,
```
setTimeout(function() {
  console.log("Job done!");
}, 500);
```
Output is 
```
>node test.js
Job done!
sleep time(ms): 538
sleep time(ms): 203
sleep time(ms): 203
sleep time(ms): 201
sleep time(ms): 201
Async job is done
```
The first sleep time this time is 538ms this time.

I tried on WIN8 PC and Raspberry PI 3B+, they showed the same behavior.

It's not a problem to me, just be interested to know why.

**Comment by jochemstoel** [comment]
I think the reason is that system-sleep executes a child node process and after the first time it has been cached in memory, so after the first time it doesn't take longer anymore.

**Comment by Charder-uGym** [comment]
@jochemstoel Thank you for the explanation. I'll close this issue.
