### ISSUE TITLE
process.execPath does not always denote the node executable

### ISSUE THREAD

**Issue by SeanSnyders** [jochemstoel/nodejs-system-sleep#5]
E.g. when run from within Electron, it is the electron executable.
So the line https://github.com/jochemstoel/nodejs-system-sleep/blob/master/module.js#L29 errors.

I use `shelljs` to run `which` to get the right node, but this can be done in many other ways:
```
var shell = require('shelljs');
nodeExec = shell.which('node');
```

so then code should be:
```
require('child_process').execSync(
		"\""+nodeExec+"\""  + " -e \"setTimeout(function () { return true; }, " + interval + ");\""
		)
```

**Comment by jochemstoel** [comment]
If you are getting this error then you don't have _deasync-promise_ installed. Did you install _system-sleep_ using _NPM install_ and did you add  _system-sleep_ in your _package.json_?

Electron and NW.JS should have no issues with deasync and therefor **not even need** to fall back on exec. I will look into it though.

**Comment by danday74** [comment]
I suggest closing this issue now it is resolved.
